services:
  # 1. Backend Service (Spring Boot)
  - type: web
    name: picklecoach-backend
    runtime: docker
    rootDir: pickleball/backend
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: DB_HOST
        sync: false # Set manually or via Railway details

      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: Vnp_TmnCode
        sync: false
      - key: Vnp_HashSecret
        sync: false
      - key: Vnp_Url
        value: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      - key: Return_url
        value: https://${FRONTEND_HOST}/payment-return
      - key: EMAIL
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: AI_SERVICE_HOST
        fromService:
          name: picklecoach-aivision
          type: web
          property: host
      - key: AI_SERVICE_URL_INTERNAL
        value: http://${AI_SERVICE_HOST}
      - key: FRONTEND_HOST
        fromService:
          name: picklecoach-frontend
          type: web
          property: host
      - key: FRONTEND_URL_PUBLIC
        value: https://${FRONTEND_HOST}

  # 2. AI Vision Service (Python Fast API)
  - type: web
    name: picklecoach-aivision
    runtime: docker
    rootDir: PickleballAIVision
    plan: free
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false

  # 3. Quiz Service (Python)
  - type: web
    name: picklecoach-quiz
    runtime: docker
    rootDir: Pickeball_AI_Quizz
    plan: free
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false

  # 4. Frontend (React Static Site)
  - type: web
    name: picklecoach-frontend
    runtime: static
    rootDir: pickleball/frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: BACKEND_HOST
        fromService:
          name: picklecoach-backend
          type: web
          property: host
      - key: VITE_API_URL
        value: https://${BACKEND_HOST}
      - key: AI_SERVICE_HOST
        fromService:
          name: picklecoach-aivision
          type: web
          property: host
      - key: VITE_AI_SERVICE_URL
        value: https://${AI_SERVICE_HOST}
